# Generated by Django 5.1.7 on 2025-03-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='space',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
