# Generated by Django 5.1.7 on 2025-03-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spaces', '0003_alter_reservation_end_time_alter_reservation_space_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
